cabal-version:      3.0
name:               ygo-pic-proxy
version:            0.1.0.0
build-type:         Simple

library
    hs-source-dirs:     src
    exposed-modules:    YgoPicProxy
    build-depends:
        base >= 4.14 && < 5,
        bytestring,
        containers,
        directory,
        filepath,
        http-client,
        http-client-tls,
        http-types,
        process,
        sqlite-simple,
        text,
        time,
        wai
    default-language:   GHC2021

executable ygo-pic-proxy
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:
        base >= 4.14 && < 5,
        ini,
        text,
        ygo-pic-proxy,
        wai,
        warp
    default-language:   GHC2021
    ghc-options:      -Wall

test-suite test
    type:               exitcode-stdio-1.0
    hs-source-dirs:     test
    main-is:            Spec.hs
    build-depends:
        base >= 4.14 && < 5,
        HUnit,
        ygo-pic-proxy,
        text
    default-language:   GHC2021


test-suite integration
    type:               exitcode-stdio-1.0
    hs-source-dirs:     test
    main-is:            Integration.hs
    build-depends:
        base >= 4.14 && < 5,
        bytestring,
        directory,
        filepath,
        http-client,
        http-client-tls,
        http-types,
        HUnit,
        network,
        sqlite-simple,
        time,
        wai,
        warp,
        ygo-pic-proxy
    default-language:   GHC2021